# Generated by Django 5.2.7 on 2025-10-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcJourney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtopic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
