# Generated by Django 5.2.7 on 2025-10-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcJourney', '0002_alter_learningtopic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='achieved_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
